# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d3d050ab204f491ca404e42cc981c221"
name = "Clarity Pixel"
handle = "clarity-pixel-2"
application_url = "https://clarity-pixel.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2641f874.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_themes,write_pixels"

[auth]
redirect_urls = [
  "https://clarity-pixel.vercel.app/auth/callback",
  "https://clarity-pixel.vercel.app/auth/shopify/callback",
  "https://clarity-pixel.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
